#pragma once
// clang-format off

// must define to compile.
combo_t key_combos[] = {};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
  [_QWERTY] = LAYOUT(
      KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    XXXXXXX,
      KC_TAB,  KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,                      KC_Y,    KC_U,    KC_I,    KC_O,    KC_P,    KC_BSLS,
      KC_BSPC, KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT,    KC_G,                      KC_H,    KC_J,    KC_K,    KC_L,    KC_SCLN, KC_QUOT,
      KC_LSFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    XXXXXXX, XXXXXXX, KC_N,    KC_M,    KC_COMM, KC_DOT,  KC_SLSH, KC_RSFT,
      KC_SPC, LOWER,   KC_LGUI, KC_LALT, RAISE,   KC_SPC,  SH_MON,  XXXXXXX, KC_ENT,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, RAISE
      ),

  [_COLEMAK] = LAYOUT(
      KC_ESC,  XXXXXXX,  KC_ENT,  XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,
      XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,
      XXXXXXX, KC_LEFT,  KC_DOWN, KC_UP,   KC_RGHT, XXXXXXX,                   XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX,
      XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  RAISE,  XXXXXXX, XXXXXXX,    XXXXXXX,    XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX,
      KC_SPC,  XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,  LOWER,  XXXXXXX, XXXXXXX,  XXXXXXX, XXXXXXX, XXXXXXX,   XXXXXXX, XXXXXXX
      ),

  [_LOWER] = LAYOUT(
      KC_ESC,  XXXXXXX, RGB_HUD, RGB_HUI, RGBRST,  XXXXXXX,                   XXXXXXX, QWERTY,  COLEMAK, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_TAB,  XXXXXXX, RGB_SAD, RGB_SAI, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_BSPC, XXXXXXX, RGB_VAD, RGB_VAI, RGB_TOG, XXXXXXX,                   KC_PSCR, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_LSFT, XXXXXXX, RGB_MOD, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_LCTL, LOWER,   KC_LGUI, KC_LALT, RAISE,   KC_SPC,  SH_MON,  XXXXXXX, KC_ENT,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, RAISE
      ),

  [_RAISE] = LAYOUT(
      KC_ESC,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    XXXXXXX,
      KC_TAB,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                      KC_6,    KC_7,    KC_8,    KC_9,    KC_0,    XXXXXXX,
      KC_DEL,  KC_GRV,  XXXXXXX, KC_LPRN, KC_RPRN, XXXXXXX,                   XXXXXXX, KC_MINS, KC_EQL,  KC_AMPR, KC_PIPE, KC_CAPS,
      KC_LSFT, KC_LBRC, KC_RBRC, KC_LCBR, KC_RCBR, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, KC_HOME, KC_PGDN, KC_PGUP, KC_END,  KC_RSFT,
      KC_RCTL, LOWER,   KC_LGUI, KC_LALT, RAISE,   KC_SPC,  SH_MON,  XXXXXXX, KC_ENT,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, RAISE
      ),

  [_ADJUST] = LAYOUT(
      KC_ESC,  XXXXXXX, RGB_HUD, RGB_HUI, RGBRST,  XXXXXXX,                   XXXXXXX, QWERTY,  COLEMAK, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_TAB,  XXXXXXX, RGB_SAD, RGB_SAI, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_BSPC, XXXXXXX, RGB_VAD, RGB_VAI, RGB_TOG, XXXXXXX,                   KC_PSCR, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_LSFT, XXXXXXX, RGB_MOD, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
      KC_LCTL, LOWER,   KC_LGUI, KC_LALT, RAISE,   KC_SPC,  SH_MON,  XXXXXXX, KC_ENT,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, RAISE
      ),

    [_HYPRLAND] = LAYOUT(
        KC_ESC,  XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,                   XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        KC_TAB,  KC_1,    KC_2,    KC_3,    KC_4,    KC_5,                      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        KC_BSPC, KC_6,    KC_7,    KC_8,    KC_9,    KC_0,                      XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        KC_LSFT, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,
        KC_LCTL, LOWER,   KC_LGUI, KC_LALT, RAISE,   KC_SPC,  SH_MON,  XXXXXXX, KC_ENT,  KC_LEFT, KC_DOWN, KC_UP,   KC_RGHT, RAISE
    ),
};